import '../../styles/globals.css'
import { PosthogAnalytics } from '../components/posthog'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <PosthogAnalytics />
        <link rel="icon" type="image/x-icon" href="/favicon.png" />
        <meta charSet="utf-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
      </head>
      <body>{children}</body>
    </html>
  )
}
